### ISSUE TITLE
Question: Is it possible to expose api interfaces?

### ISSUE THREAD

**Issue by fikani** [LaMbA3/typeorm-query-parser#3]
Hello!!
Firstly, thank you for this repository 😃 !! It's a great idea.

My question is regarding the interfaces: `IOptionsObject   IQueryTypeOrm  IQueryObject`

Do you think the interfaces could be exported?

```
export interface IQueryObject {
    select?: string;
    join?: string;
    sort?: string;
    cache?: string;
    limit?: string;
    page?: string;
    filter?: string;
}
```

I'd like to use them in my controllers like: 
```
find(@Query() query: IQueryObject): Promise<User[]> {
    const parser = new QueryBuilder({}).build(query);
}
```

Also, the constructor of QueryBuilder is like this:
`constructor(configuration?: object);`

Should it be like?
`constructor(configuration?: IOptionsObject);`

Great work so far 👍

**Comment by LaMbA3** [comment]
HI, Thank you for your feedback. I will fix all the issues you mentioned today. I will also improve documentation. On Sep 3, 2020 16:40, Afif <notifications@github.com> wrote:

Hello!!

Firstly, thank you for this repository 😃 !! It's a great idea.

My question is regarding the interfaces: IOptionsObject   IQueryTypeOrm  IQueryObject

Do you think the interfaces could be exported?

export interface IQueryObject {

    select?: string;

    join?: string;

    sort?: string;

    cache?: string;

    limit?: string;

    page?: string;

    filter?: string;

}



I'd like to use them in my controllers like:

find(@Query() query: IQueryObject): Promise<User[]> {

    const parser = new QueryBuilder({}).build(query);

}



Also, the constructor of QueryBuilder is like this:

constructor(configuration?: object);

Should it be like?

constructor(configuration?: IOptionsObject);

Great work so far 👍
